export const INITIAL_DATA = [
  {
    title: '오늘',
    what: '뭐',
    when: '안합니다',
    startTime: '00:00',
    endTime: '00:00',
    id: 0,
    todo: true,
    done: false,
    archive: false,
  },
  {
    title: '내일',
    what: '뭐',
    when: '안합니다',
    startTime: '00:00',
    endTime: '00:00',
    id: 1,
    todo: true,
    done: false,
    archive: false,
  },
  {
    title: '모레',
    what: '뭐',
    when: '안합니다',
    startTime: '00:00',
    endTime: '00:00',
    id: 2,
    todo: true,
    done: false,
    archive: false,
  },
  {
    title: '이제',
    what: '뭐',
    when: '안합니다',
    startTime: '00:00',
    endTime: '00:00',
    id: 3,
    todo: true,
    done: false,
    archive: false,
  },
];
